default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     sh "flutter clean"
     sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
     firebase_app_distribution(
       app: "1:821004262009:android:b384c31964fca9092952a8",
       firebase_cli_token: "1//039Q2ljdEfrRkCgYIARAAGAMSNwF-L9Ir4nQ6B0i09KzfcDnttKxwyYj7DQJHIookt6PhJ9sj5yCWU4cw1uaqrlv2ZldrWgNOKLI",
       android_artifact_type: "APK",
       android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
       testers: "bode.elgohary69@gmail.com,samy.elmenshawy96@gmail.com", 
       release_notes: "we are testing the production build of Hecta app",
     )
   end
 end